### ISSUE TITLE
Garden not refreshing auth tokens 

### ISSUE THREAD

**Issue by graemechristie** [garden-io/garden#2330]
## Bug

Garden does not refresh auth tokens in the same manner that kubectl does. When using garden with AKS and RBAC set up,  the token in the kubeconfig file will expire and garden does not fetch a new one (as for e.g. kubectl does). I need to do a manual `kubectl get pods` or other arbitrary kubectl command then garden will continue working. This issue looks to have been reported several years ago, acknowledged, but then closed as stale

https://github.com/garden-io/garden/issues/1043

### Current Behavior

When using AKS and a cluster with RBAC enabled, auth tokens will time out and garden commands will return

![image](https://user-images.githubusercontent.com/1361894/112846100-3f0bb680-90d8-11eb-9e2c-9b4524c52020.png)

### Expected behavior

When an auth token has expired, garden will aquire a new one using the refresh mechanism that kubectl uses.
### Workaround

We need to manually run an arbitrary kubectl commmand when we get the above error message.

### Suggested solution(s)

Update you k8s client code to refresh auth tokens when they expire.

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** AKS

`garden version`

0.12.19

**Comment by edvald** [comment]
Thanks @graemechristie. I think we might need to update our k8s client library (which we didn't write ourselves), I sort of suspect this has been fixed upstream. I'll take a look.

**Comment by ITHedgeHog** [comment]
If it does @edvald you can close this too https://github.com/garden-io/garden/issues/2311

**Comment by edvald** [comment]
Perhaps I could trouble you to give the build a spin, to see if it does the job? https://app.circleci.com/pipelines/github/garden-io/garden/8935/workflows/e6fe4f59-061f-49a3-b638-73ab20964af3/jobs/114125/artifacts

The first four artifacts are the packaged builds for the PR. Just need to curl and extract the appropriate archive and run the binary from there, instead of the installed one. _Note: on macOS you might bump into permission issues if you download via the browser, better to curl/wget from the terminal_.

**Comment by ITHedgeHog** [comment]
Grabbing it now

**Comment by ITHedgeHog** [comment]
@edvald Sorry for the delay, still getting this when in use: 

StatusCodeError from Kubernetes API - 401 - {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","mes
sage":"Unauthorized","reason":"Unauthorized","code":401}

That is with garden 0.12.20

**Comment by ITHedgeHog** [comment]
Sorry I should clarify, that it works initially - but leaving garden dev running eventually returns that error message.

**Comment by edvald** [comment]
Ah I see, that does clarify. That we can probably handle on our side by automatically retrying the requests. I'll need to inspect their code but I suspect the client library doesn't do that sort of thing out of the box.

**Comment by ITHedgeHog** [comment]
I've just rested this on Garden 0.12.21

This is after a reboot of my development system, I open PowerShell and run garden dev (Without kubectl version) before hand.

[garden_dev_error.txt](https://github.com/garden-io/garden/files/6397851/garden_dev_error.txt)

Obviously, if I run kubectl version first the token is there - it doesn't look like it requests one at all currently?

**Comment by eysi09** [comment]
So this happens on the first run of `garden dev`? And presumably other Garden commands as well, right?

We bumped the K8s client lib to the latest version before this release to ensure us being on an older version wasn't causing the original issue (from 1.14.0 to 1.14.3). Wonder if a regression was introduced on their end between releases. 

I did scan the commits in K8s client lib but didn't see anything unusual.

**Comment by ITHedgeHog** [comment]
Yep, I have just restarted my machine again and validated that garden build|test|validate exhibit the same behaviour.

**Comment by ITHedgeHog** [comment]
I see that in go this is the bit that makes it work https://github.com/kubernetes/client-go/tree/f6ce18ae578c8cca64d14ab9687824d9e1305a67/plugin/pkg/client/auth/azure

Looking through the repo for the node package you use I came across this: https://github.com/kubernetes-client/javascript/issues/358 

It looks like it might be a known issue that is currently frozen.

Let me know if I'm way off base with this assumption?

**Comment by eysi09** [comment]
Interesting, that issue makes me wonder why it worked in the first place. 

But we're currently working on a fix on our end that catches these kind of errors and refreshes the token—via the K8s client API though, so the assumption is that that works in the first place. 

And just to be sure, this works on Garden v0.12.20? You can grab it from here: https://github.com/garden-io/garden/releases/tag/0.12.20 while we work on a fix but it doesn't have dev-mode. Also, you might want to download it via curl if you're on macOS because otherwise it was complain about downloaded binaries.

If this version works for you, it suggests we should downgrade the K8s client lib back to 1.14.0. I'll also open a issue in their repo on the topic.

**Comment by eysi09** [comment]
Just to be sure I'm heading in the right direction here, is this the RBAC functionality from Azure that you believe is causing the issues: https://docs.microsoft.com/en-us/azure/aks/manage-azure-rbac

(cc @graemechristie, @ITHedgeHog)

**Comment by graemechristie** [comment]
yes @eysi09 - that is the feature we are using with Azure AKS (although I'm not sure if the openId/token expiry issue is Azure specific, or if the openId standard for tokens in kubenetes is an open standard/feature utilsed by AKS) .. I had assumed the latter as kubectl seems to have native support for it.

**Comment by graemechristie** [comment]
Looking at #1043 - it seems this also affects other services on aws, or anything using kubectl exec plugins like heptio-authenticator-aws - so it seems the AKS support in kubectl is via a "kubelogin" plugin (presumably this https://github.com/Azure/kubelogin)  .. e.g. my kubeconfig uses:

![image](https://user-images.githubusercontent.com/1361894/118228117-41757480-b4bc-11eb-89b5-8589cab54cef.png)

**Comment by twelvemo** [comment]
We reproduced the issue internally. However when I used [kubelogin]( https://github.com/Azure/kubelogin) and followed these instructions https://github.com/Azure/kubelogin#azure-cli-token-login-non-interactive I did not face any problems. After not having interacted with the cluster for more than 2 hours I was able to deploy with garden, @eysi09 did the same but without using kubelogin and ran into the missing auth token issue. 
 @graemechristie your kubeconfig looks pretty much like mine with kubelogin, but you are still experiencing auth issues with garden?

**Comment by graemechristie** [comment]
That makes sense @twelvemo - I probably did not understand the role of kubelogin in respect to those tokens. I will give this a go but I suspect it will resolve our issue.

**Comment by twelvemo** [comment]
sounds good! Would love to hear if it works @graemechristie then we can put this in our docs.

**Comment by eysi09** [comment]
cc @ITHedgeHog ☝️ 

We'll also add an entry to our Troubleshooting guide on this (assuming it works).

**Comment by ITHedgeHog** [comment]
Thanks, @eysi09 @twelvemo I'm giving it a try today.

**Comment by ITHedgeHog** [comment]
@eysi09 @twelvemo That appears to have resolved it for me, I've been working for 5 hours non-stop now without having to run any manual kubectl commands.

**Comment by eysi09** [comment]
That's great news! I'll leave this open and flag it as a discussion for now so that it's visible to others. We'll also need to add this to our docs.

**Comment by eysi09** [comment]
See: https://github.com/garden-io/garden/pull/2453
